### ISSUE TITLE
Avatar not being updated after rebuild 

### ISSUE THREAD

**Issue by BirukMg** [luckyseven/avatars#4]
Suppose that I update the data given to the Avatar widget at run time(for example, after clicking a button) but the avatar is not updated. For example, if I give it an updated image network URL, the avatar displays the old data. Is there any way to force rebuilding the widget when the input changes?

**Comment by cody1024d** [comment]
@luckyseven Can you please merge the mentioned PR, and release a new version? This framework is perfect for my use-case, but I need to be able to dynamically change the image

**Comment by elijahjpassmore** [comment]
@cody1024d If you need to use it now, just put this in your pubspec.yaml in place of the current one:
```
  avatars:
    git:
      url: git://github.com/elijahjpassmore/avatars.git
      ref: master
```
That should suffice until the PR is merged or another solution is implemented.
